# Generated by Django 2.1.4 on 2019-02-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Дрон')),
                ('connection_ip', models.CharField(max_length=200)),
                ('camera_color', models.CharField(default='http://', max_length=200, verbose_name='Цветная камера')),
                ('camera_thermal', models.CharField(default='http://', max_length=200, verbose_name='Термальная камера')),
                ('outer_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Удаленный ID')),
                ('work_air_speed', models.FloatField(default=2, verbose_name='Air speed')),
                ('work_ground_speed', models.FloatField(default=5, verbose_name='Ground speed')),
                ('work_altitude', models.FloatField(default=30, verbose_name='Work altitude')),
            ],
            options={
                'verbose_name_plural': 'Дроны',
                'verbose_name': 'Дрон',
            },
        ),
        migrations.CreateModel(
            name='DroneCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип команды')),
                ('point', models.CharField(blank=True, max_length=200, null=True, verbose_name='Координаты')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор')),
                ('status', models.CharField(default='0', max_length=200, verbose_name='Статус')),
                ('is_sync', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('is_async', models.BooleanField(default=False, verbose_name='Асинхронность')),
                ('route_uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор маршрута')),
                ('outer_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Внешний ID')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Drone', verbose_name='Коптер')),
            ],
            options={
                'verbose_name_plural': 'Команды',
                'verbose_name': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='DronePlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('camera', models.CharField(max_length=200, verbose_name='Камера')),
                ('state', models.CharField(max_length=200, verbose_name='Состояние')),
                ('state_doors', models.CharField(max_length=200, verbose_name='Состояние дверей')),
                ('state_guides', models.CharField(max_length=200, verbose_name='Состояние направляющих')),
                ('state_lift', models.CharField(max_length=200, verbose_name='Состояние платформы')),
                ('state_luk', models.CharField(max_length=200, verbose_name='Состояние люка')),
                ('coordinates_lat', models.CharField(default='53.474011', max_length=200, verbose_name='Координаты (широта)')),
                ('coordinates_lon', models.CharField(default='49.203084', max_length=200, verbose_name='Координаты (долгота)')),
                ('command', models.CharField(max_length=200, verbose_name='Команда')),
            ],
            options={
                'verbose_name_plural': 'Базы',
                'verbose_name': 'База',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='ExchangeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип объекта')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='УИД')),
            ],
            options={
                'verbose_name_plural': 'Пакеты обмена',
                'verbose_name': 'Пакет обмена',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('coordinates_lon', models.CharField(max_length=200, verbose_name='Долгота')),
                ('coordinates_lat', models.CharField(max_length=200, verbose_name='Широта')),
                ('coordinates_alt', models.CharField(max_length=200, verbose_name='Высота')),
                ('air_speed', models.CharField(max_length=200, verbose_name='Скорость ветра')),
                ('ground_speed', models.CharField(max_length=200, verbose_name='Скорость движения')),
                ('is_armable', models.CharField(max_length=200, verbose_name='Способен вооружиться')),
                ('is_armed', models.CharField(max_length=200, verbose_name='Вооружен')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('last_heartbeat', models.CharField(max_length=200, verbose_name='Последний отклик')),
                ('mode', models.CharField(max_length=50, verbose_name='Режим')),
                ('battery_voltage', models.CharField(max_length=200, verbose_name='Напряжение батареи')),
                ('battery_level', models.CharField(max_length=5, verbose_name='Уровень заряда батареи')),
                ('gps_fixed', models.CharField(max_length=5, verbose_name='Спутников зафиксировано')),
                ('is_uploaded', models.BooleanField(default=False, verbose_name='Загружено')),
                ('connection', models.BooleanField(default=False, verbose_name='Соединение')),
                ('outer_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Удаленный ID')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор')),
                ('drone', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Drone', verbose_name='Коптер')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name_plural': 'Истории',
                'verbose_name': 'История',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.TextField(verbose_name='Координаты точек')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('status', models.CharField(default='0', max_length=200, verbose_name='Статус')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор')),
                ('is_sync', models.BooleanField(default=False, verbose_name='Синхронизировано')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Drone', verbose_name='Коптер')),
            ],
            options={
                'verbose_name_plural': 'Маршруты',
                'verbose_name': 'Маршрут',
            },
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_pane.DronePlane'),
        ),
    ]
