# Generated by Django 2.1.5 on 2019-02-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Event', verbose_name='Событие'),
        ),
    ]
