# Generated by Django 2.1.5 on 2019-03-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0002_auto_20190201_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='drone',
            name='rtl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Домашняя точка'),
        ),
        migrations.AddField(
            model_name='route',
            name='commands',
            field=models.TextField(default=[], verbose_name='Координаты точек'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.Event', verbose_name='Событие'),
        ),
    ]
