# Generated by Django 2.1.5 on 2019-03-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0003_auto_20190305_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_pane.Drone', verbose_name='Дрон'),
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.Event', verbose_name='Событие'),
        ),
    ]
