# Generated by Django 2.1.5 on 2019-03-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0004_auto_20190311_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='droneplane',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.DroneCommand', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='event',
            name='drone_plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.DronePlane', verbose_name='Взлетная площадка'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.Route', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_pane.Drone', verbose_name='Дрон'),
        ),
    ]
