# Generated by Django 2.1.7 on 2019-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0005_auto_20190314_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='camera_color',
            field=models.CharField(blank=True, default='http://', max_length=200, null=True, verbose_name='Цветная камера'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='camera_thermal',
            field=models.CharField(blank=True, default='http://', max_length=200, null=True, verbose_name='Термальная камера'),
        ),
    ]
