# Generated by Django 2.1.7 on 2019-03-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0006_auto_20190324_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('stream_input', models.URLField(default='http://www.')),
                ('nn_required', models.BooleanField(default=False, verbose_name='Слой нейросети')),
                ('telemetry_required', models.BooleanField(default=False, verbose_name='Слой телеметрии')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('fps', models.IntegerField(default=0)),
                ('output_name', models.CharField(max_length=200)),
                ('record_path', models.CharField(max_length=200)),
                ('tmp_image_path', models.CharField(max_length=200)),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор')),
            ],
        ),
        migrations.AlterField(
            model_name='drone',
            name='camera_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_color', to='control_pane.Stream'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='camera_thermal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_thermal', to='control_pane.Stream'),
        ),
    ]
