# Generated by Django 2.1.7 on 2019-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0007_auto_20190324_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_input',
            field=models.CharField(default='http://www.', max_length=200),
        ),
    ]
