# Generated by Django 2.1.7 on 2019-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0008_auto_20190324_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='status',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
