# Generated by Django 2.1.7 on 2019-03-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0009_stream_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='output_name',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='stream_input',
        ),
        migrations.AddField(
            model_name='stream',
            name='protocol',
            field=models.CharField(default='mjpeg', max_length=200, verbose_name='Протокол передачи'),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_in',
            field=models.CharField(default='http://www.example.com', max_length=200, verbose_name='Ссылка на поток'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='fps',
            field=models.IntegerField(default=0, verbose_name='Кадров в секунду'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='record_path',
            field=models.CharField(default='root/drone/{{title}}/record/', max_length=200, verbose_name='Путь сохранения видео'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.BooleanField(default='0', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='tmp_image_path',
            field=models.CharField(default='root/drone/{{title}}/last_image', max_length=200, verbose_name='Путь сохранения картинки'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
