# Generated by Django 2.1.7 on 2019-03-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_pane', '0010_auto_20190328_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.BooleanField(default=False, max_length=2, verbose_name='Статус'),
        ),
    ]
